[language-server.vtsls]
command = "vtsls"
args = [ "--stdio" ]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "typescript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]

[[language]]
name = "javascript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]

[[language]]
name = "tsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]

[[language]]
name = "jsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]
