[tools]
usage = "latest"

atuin = { version = "18.10" }
bat = { version = "0.26" }
bob = { version = "4.1" }
cloudflared = { version = "2025.10" }
delta = { version = "0.18" }
duf = { version = "0.9" }
dust = { version = "1.2" }
eza = { version = "0.23" }
"aqua:pkolaczk/fclones" = { version = "0.35" }
fd = { version = "10.3" }
"aqua:printfn/fend" = { version = "1.5" }
hexyl = { version = "0.16" }
hyperfine = { version = "1.19" }
just = { version = "1.43" }
lazydocker = { version = "0.24" }
lazygit = { version = "0.56" }
"aqua:ouch-org/ouch" = { version = "0.6" }
"aqua:dalance/procs" = { version = "0.14" }
ripgrep = { version = "15.1" }
sops = { version = "3.11" }
starship = { version = "1.24" }
tlrc = { version = "1.12" }
tree-sitter = { version = "0.25" }
watchexec = { version = "2.3" }
xh = { version = "0.25" }
yazi = { version = "25.5" }
zellij = { version = "0.43" }
"aqua:zk-org/zk" = { version = "0.15" }
zoxide = { version = "0.9" }

[settings]
experimental = true
disable_backends = ["asdf"]
idiomatic_version_file_enable_tools = []
exec_auto_install = false
not_found_auto_install = false

[settings.status]
missing_tools = "never"
